#!/usr/bin/with-contenv bash

cd /app/kanzi || exit

exec \
	s6-setuidgid abc gunicorn -b 0.0.0.0:8000 --certfile /config/keys/kanzi/certificate.pem --keyfile /config/keys/kanzi/private-key.pem alexa:app
